### ISSUE TITLE
GreetingAtMorning#nowをTokyoDomeEventに組み込む

### ISSUE THREAD

**Issue by otofu-square** [feedforce/ruboty-sebastian#13]
TokyoDomeEventに現状のGreetingAtMorning#nowを組み込むと、
TokyoDomeEventの各メソッドの引数を省略することができる上に、
GreetingAtBeforeClosing#call内でイベントを取得する際にもスマートに実装することができる。

**Comment by mgi166** [comment]
https://github.com/feedforce/ruboty-sebastian/pull/15

で対応済みなので、close
